name: Terraform AWS Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy the infrastructure"
        required: false
        default: "false"

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Terraform Init
      env:
        AWS_REGION: ${{ vars.AWS_REGION }}
      run: terraform init

    - name: Terraform Plan
      env:
        AWS_REGION: ${{ vars.AWS_REGION }}
      run: terraform plan

    - name: Terraform Apply
      if: github.event.inputs.destroy != 'true'
      env:
        AWS_REGION: ${{ vars.AWS_REGION }}
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: github.event.inputs.destroy == 'true'
      env:
        AWS_REGION: ${{ vars.AWS_REGION }}
      run: terraform destroy -auto-approve
